// <auto-generated />
using ArthrpodaASP.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Arthropoda.Migrations
{
    [DbContext(typeof(ArthropodaDbContext))]
    [Migration("20211210052159_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21");

            modelBuilder.Entity("ArthrpodaASP.Models.Family", b =>
                {
                    b.Property<int>("FamilyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("FamilyId");

                    b.ToTable("Familys");
                });

            modelBuilder.Entity("ArthrpodaASP.Models.Familyinsect", b =>
                {
                    b.Property<int>("FamilyinsectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("FamilyinsectId");

                    b.ToTable("Familyinsects");
                });

            modelBuilder.Entity("ArthrpodaASP.Models.Genera", b =>
                {
                    b.Property<int>("GeneraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("GeneraId");

                    b.ToTable("Generas");
                });

            modelBuilder.Entity("ArthrpodaASP.Models.InfraOrder", b =>
                {
                    b.Property<int>("InfraOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("InfraOrderId");

                    b.ToTable("InfraOrders");
                });

            modelBuilder.Entity("ArthrpodaASP.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
